sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t achowdhury80/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true achowdhury80/react-test npm test

after_success:
  - docker build -t achowdhury80/multi-client ./client
  - docker build -t achowdhury80/multi-nginx ./nginx
  - docker build -t achowdhury80/multi-server ./server
  - docker build -t achowdhury80/multi-worker ./worker

